# Generated by Django 5.1.2 on 2025-02-21 19:05

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import hunt.models
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        # ... rest of your migration operations ...
    ] 