# Generated by Django 5.1.2 on 2025-02-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='lobby',
        ),
        migrations.RemoveField(
            model_name='team',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='team',
            name='score',
        ),
        migrations.RemoveField(
            model_name='team',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='team',
            name='submissions',
        ),
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
