# Generated by Django 5.0 on 2023-12-19 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='requires_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TeamProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completion_time', models.DateTimeField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='question_photos/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='hunt.question')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='hunt.team')),
            ],
            options={
                'ordering': ['completion_time'],
                'unique_together': {('team', 'question')},
            },
        ),
    ] 