# Generated by Django 5.0 on 2023-12-20 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0002_add_team_progress'),
    ]

    operations = [
        migrations.RunSQL(
            # Add column with default
            sql="""
            ALTER TABLE hunt_teammember 
            ADD COLUMN name VARCHAR(100) DEFAULT '';
            """,
            reverse_sql="""
            ALTER TABLE hunt_teammember
            DROP COLUMN name;
            """
        ),
        migrations.RunSQL(
            # Copy role values to name
            sql="""
            UPDATE hunt_teammember
            SET name = role
            WHERE name = '';
            """,
            reverse_sql="SELECT 1;"  # Dummy for reverse migration
        ),
    ]