# Generated by Django 5.1.2 on 2025-02-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0003_remove_lobby_code_remove_lobby_leader_lobby_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='code',
            field=models.CharField(blank=True, max_length=4, unique=True),
        ),
        migrations.AddField(
            model_name='lobby',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
