# Generated by Django 5.1.2 on 2025-04-08 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0003_add_name_to_teammember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lobby',
            options={'verbose_name_plural': 'Lobbies'},
        ),
        migrations.AddField(
            model_name='lobby',
            name='last_accessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lobby',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hunt.race'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(blank=True, max_length=255, null=True)),
                ('answered_correctly', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('points_awarded', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requires_photo', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='answer_photos/')),
                ('matched_with', models.CharField(blank=True, max_length=255, null=True)),
                ('match_type', models.CharField(blank=True, max_length=50, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='hunt.question')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='hunt.team')),
            ],
            options={
                'ordering': ['submitted_at'],
                'unique_together': {('team', 'question')},
            },
        ),
        migrations.CreateModel(
            name='TeamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_correctly', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.IntegerField(default=0)),
                ('points_awarded', models.IntegerField(default=0)),
                ('requires_photo', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='answer_photos/')),
                ('photo_uploaded', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_answers', to='hunt.question')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='hunt.team')),
            ],
            options={
                'ordering': ['answered_at'],
                'unique_together': {('team', 'question')},
            },
        ),
        migrations.CreateModel(
            name='TeamRaceProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_question_index', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_progress', to='hunt.race')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_progress', to='hunt.team')),
            ],
            options={
                'unique_together': {('team', 'race')},
            },
        ),
    ]
