# Generated by Django 5.1.2 on 2025-04-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0008_add_missing_last_accessed'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='hunt_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamraceprogress',
            name='photo_questions_completed',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
