# Generated by Django 5.1.2 on 2025-02-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0002_remove_team_lobby_remove_team_progress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobby',
            name='code',
        ),
        migrations.RemoveField(
            model_name='lobby',
            name='leader',
        ),
        migrations.AddField(
            model_name='lobby',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='lobbies', to='hunt.team'),
        ),
    ]
